version: '2.1'
orbs:
  email: cinotify/email@1.2.3
workflows:
  example-workflow:
    jobs:
      - email/send:
          body: 'Configure this notification at https://www.cinotify.cc/'
          subject: CircleCI job started
          to: anujscool99@gmail.com
      - build_deploy:
          machine:
            image: ubuntu-latest
          steps:
            -checkout
            - run:
                name: Run-testcases
                command:
                  sudo apt-get update
                  sudo apt install npm
                with:
                  build: npm run build
                  start: npm run dev
