version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  email: cinotify/email@1.2.1
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run build' # run a custom app build step
      - cypress/run:
          requires:
            - cypress/install
          #record: true # record results on Cypress Dashboard
          parallel: true # split all specs across machines
          parallelism: 10 # use 4 CircleCI machines to finish quickly
          group: 'all tests' # name this group "all tests" on the dashboard
          start: 'npm run dev' # start server before running tests
      - email/send:
          requires:
            - cypress/run
          body: 'CircleCI job ended Succesfully'
          subject: CircleCI job ended Succesfully
          to: anujsahatpure16@gmail.com    
      
    