version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0

workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run build' 
          # start: 'npm run dev'

      - cypress/run:
          start: 'npm run dev'