version: 2.1
orbs:
  email: cinotify/email@1.2.0

workflows:
  example-workflow:
    jobs:
      - email/send:
          body: ./README.html
          subject: CircleCI job started
          to: anujscool99@gmail.com
           