version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - cypress/install
      - cypress/setup:
          build: npm run build 
          install-command: npm start dev 
workflows:
  example-workflow:
    jobs:
      - example-job